from typing import Literal

from pygame.event import Event

from events.event_type import EventType


class MouseWheelEvent:
    type: Literal[EventType.MOUSE_WHEEL]
    """
    EventType.MOUSE_WHEEL
    """

    flipped: bool
    """
    Whether the values in X and Y will be opposite
    """

    x: int
    """
    The amount scrolled horizontally, positive to the right and negative to the left
    """

    y: int
    """
    The amount scrolled vertically, positive away from the user and negative toward the user
    """

    touch: bool
    """
    Whether or not the event was generated by a touch input device
    """

    precise_x: float
    """
    The amount scrolled horizontally, positive to the right and negative to the left
    """

    precise_y: float
    """
    The amount scrolled vertically, positive away from the user and negative toward the user
    """

    def __init__(self, event: Event):
        self.type = EventType.MOUSE_WHEEL
        self.flipped = event.flipped
        self.x = event.x
        self.y = event.y
        self.touch = event.touch
        self.precise_x = event.precise_x
        self.precise_y = event.precise_y

    def __repr__(self):
        return f"<{self.__class__.__name__}: {self.__dict__}>"
